spring:
  application:
    name: order-service

server:
  port: 8081

management:
  endpoints:
    web:
      exposure.include: '*'
  endpoint:
    health:
      show-details: ALWAYS

# By having spring-cloud-starter-netflix-eureka-client on the classpath, your application automatically
# registers with the Eureka Server

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
