spring:
  application:
    name: spring-boot-admin

  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin}

  boot:
    admin:
      discovery:
        ignored-services: spring-boot-admin

eureka:
  instance:
    prefer-ip-address: true

server:
  port: 9999

management:
  endpoints:
    web:
      exposure.include: '*'
  endpoint:
    health:
      show-details: ALWAYS



# By having spring-cloud-starter-netflix-eureka-client on the classpath, your application automatically
# registers with the Eureka Server

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
